config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :photo, styles: {large: "600x600>", medium: "350x300>", thumb: "70x70>" }
  validates_attachment :photo, presence: true
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  protect_from_forgery except: :index
  def new
    @post = Post.new
  end

  def index
    @posts = Post.paginate(page: params[:page],per_page: 2).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:caption, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaRoR</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script type="text/javascript">

      function infiniteScrollHelper(){
        pagination_element = document.querySelectorAll('.pagination .next_page')
        if(pagination_element.length > 0)
          more_posts_url = pagination_element[0].getAttribute('href')
        else
          more_posts_url = ""
        if(more_posts_url && (window.pageYOffset >= document.body.clientHeight - window.innerHeight) )
        {
          document.querySelector('.pagination').innerHTML = '<p> Loading older posts ........ </p>'
          var head= document.getElementsByTagName('head')[0];
          var script= document.createElement('script');
          script.type= 'text/javascript';
          ques_index=more_posts_url.indexOf('?')
          if(more_posts_url.indexOf(".js")==-1)
            script.src= more_posts_url.substring(0,ques_index)+".js?"+more_posts_url.substring(ques_index+1)
          else
            script.src= more_posts_url
          script.async = true;
          head.appendChild(script);
        }
      }

      if( document.querySelectorAll('.pagination').length  && document.querySelectorAll('#posts').length )
      {
        window.addEventListener('scroll',infiniteScrollHelper);
      }

    </script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true, html: { multipart: true } do |form| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being created:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :caption %><br>
    <%= form.text_field :caption %>
  </p>

  <p>
    <%= form.label :photo %><br>
    <%= form.file_field :photo %>
  </p>

  <p>
    <%= form.submit %>
  </p>
  <br>
  <%= link_to 'Back to Home', root_path %>
<% end %>

app/views/posts/_post.html.erb
<div class="">
  <%= link_to post_path(post) do %>
    <h4><%= post.caption %></h4>
    <%= image_tag post.photo.url(:medium) %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h3>Edit post :</h3>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>InstaRoR</h1>
<p><%= link_to 'Create new post', new_post_path %></p>
<br>
<div class="" id="posts">
  <%= render @posts %>
</div>

<%= will_paginate @posts %>

app/views/posts/index.js.erb
document.querySelector('#posts').insertAdjacentHTML( 'beforeend', '<%= j render @posts %>');
<% if @posts.next_page %>
  document.querySelector('.pagination').outerHTML = "<%= j will_paginate @posts %>";
<% else %>
  window.removeEventListener('scroll',infiniteScrollHelper);
  document.querySelector('.pagination').innerHTML = "<br><p>Good job reaching here. You have seen all the posts. Nothing more to show :D</p><br>";
<% end %>

app/views/posts/new.html.erb
<h3>Create new post :</h3>
<%= render 'form' %>

app/views/posts/show.html.erb
<h2>Post details</h2>

<h3><%= @post.caption %></h3>
<%= image_tag @post.photo.url(:large) %>

<p>
  <%= link_to 'Back To Home', posts_path %><br>
  <%= link_to 'Edit', edit_post_path(@post) %><br>
  <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure you want to delete this post ?' } %><br>
</p>